# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Test CI

on:
  push:
    branches: [ FinalProject ]
  pull_request:
    branches: [ FinalProject ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Front
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ./Front/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm start
    - name: Cypress run
      uses: cypress-io/github-action@v2.9.7
      env:
          CYPRESS_host: http://api.dev.local
          CYPRESS_port: 3000
      with:
        start: npm run start
        wait-on: http://api.dev.local:3000
        wait-on-timeout: 120
        browser: chrome
        headless: true
        spec: cypress/integration/cy1.spec.js
        
        
