# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Test CI

on:
  push:
    branches: [ FinalProject ]
  pull_request:
    branches: [ FinalProject ]

jobs:
  build:

    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./Front
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: run back end test
      run: ./ExecBack.sh
      timeout-minutes: 30
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ./Front/package-lock.json
        # working-directory: ./Front
    - run: npm ci
      working-directory: ./Front
    - run: npm run build --if-present
      working-directory: ./Front
    - run: npm test
      working-directory: ./Front
    - name: Cypress run
      uses: cypress-io/github-action@v2.9.7
      with:
        working-directory: ./Front
        start: npm start
        wait-on: http://localhost:3000
        wait-on-timeout: 120
        browser: chrome
        headless: true
        config: baseUrl=https://localhost:3000/
        spec: cypress/integration/cy1.spec.js
